### ISSUE TITLE
Timestamp resolution not granular enough

### ISSUE THREAD

**Issue by alexwilson1** [census-instrumentation/opencensus-python#1019]
Hey team,

I have been experiencing a problem where logs in Azure Log Analytics are out of order. This is due to the timestamp resolution not being high enough (e.g. if you log twice, two nanoseconds apart, they get sent with the same timestamp).

This is shown by the screenshot below that is produced by the following code:

![image](https://user-images.githubusercontent.com/25535957/113111278-bbb79700-91a3-11eb-85e3-1a0874cd2d4a.png)

```
if app_insights_connection_str:
    logger.addHandler(AzureLogHandler(
        connection_string=app_insights_connection_str, export_interval=EXPORT_INTERVAL_SECS)
    )

for i in range(10000):
    for j in range(10):
        logger.info(f'log loop {i}, {j}')
    time.sleep(1)
```

I think this is due to the code in `logging\_init_.py` line 287 that produces millisecond level timestamps:

```
    def __init__(self, name, level, pathname, lineno,
                 msg, args, exc_info, func=None, sinfo=None, **kwargs):
        """
        Initialize a logging record with interesting information.
        """
        ct = time.time()
        self.name = name
        self.msg = msg
```

Perhaps this could be fixed by logging at nanosecond resolution using `time.time_ns()`? Alternatively we could have a separate counter that counts up and submits it as part of the default envelope, thus giving us ordering information.

Thanks!

Alex

**Comment by csm10495** [comment]
I just hit this exact same thing. Timestamps match which lead to me not being able to see the actual order events happened in kusto. 

If it helps I'm on Python 3.9.7 x64 on Windows.

**Comment by csm10495** [comment]
For fun i tried a little test locally: 

```
In [10]: d = []

In [11]: for i in range(100): d.append(time.time())

In [12]: len(d)
Out[12]: 100

In [13]: len(set(d))
Out[13]: 1

In [14]: d = []

In [15]: for i in range(100): d.append(time.time_ns())

In [16]: len(d)
Out[16]: 100

In [17]: len(set(d))
Out[17]: 1
```

.. so it turns out that even if python changed to `time_ns()` it wouldn't help as at least on my host the precision for timestamps isn't high enough in either case.

**Comment by csm10495** [comment]
Have we considered adding a message counter to custom_dimensions? Then in kusto we could sort by timestamp then message counter to ensure logs are in the correct order.

I'm sure this can be done as a one off, but may make sense to have the capability available for all.

**Comment by csm10495** [comment]
@lzchen I understand, but does it make sense to allow something like this to be built-in? Otherwise currently the user would have to manage the message counter... while it could be centralized inside the log handler itself.

**Comment by lzchen** [comment]
Possibly. There are a couple of reasons why we probably wouldn't want to do this.

1. No one has asked for this level of granularity (ns) in timestamp with Opencensus before, so this would probably be a one-off specific implementation detail in the Opencensus azure exporters. That means that users would have to onboard and understand the purpose of this dimension appearing, and how they would use it in kusto (to sort by timestamp), which could possibly cause more confusion. If this is the case, using your own custom dimensions would be more ideal.
2. Continuing for (1), if granularity of values (in ns) is important for a majority of users, it should be implemented in the ingestion service, not the SDK.
3. Adding a field into custom dimensions is expensive to store and query, which is why the guidance is for users to add only the custom dimensions they require. Having a "count" appear in custom dimensions may be confusing and unnecessary for users who do not care for this feature.

**Comment by lzchen** [comment]
@alexwilson1 
Workaround would involve implementing your own counter in custom dimensions. Does this solve your issue?

**Comment by lzchen** [comment]
Closing for now. Feel free to reopen if workaround does not work.
