### ISSUE TITLE
[Azure exporter] Flush log exporter on exit

### ISSUE THREAD

**Issue by lzchen** [census-instrumentation/opencensus-python#1085]

**Comment by Willem-J-an** [comment]
Until this feature is implemented, I would like to frankenstein a workaround. I'm thinking to call logging.shutdown() and then explicitly wait until the Worker threads are terminated, would this work? Would there be any other workaround to ensure logs are flushed? 20 second sleep at the end is quite painful.

**Comment by Willem-J-an** [comment]
This seems to work perfectly for my use case:
``` python
# Add short export_interval to every AzureLogHandler and AzureExporter instance
log_handler = AzureLogHandler(export_interval=2)
exporter=AzureExporter(export_interval=2)
``` 

``` python
# At the end of everything, manually shutdown the alive logging workers, until the threads are gone.
from opencensus.ext.azure.common.exporter import Worker as TraceWorker
from opencensus.ext.azure.log_exporter import Worker as LogWorker

while True:
    log_workers = [
        thread
        for thread in threading.enumerate()
        if isinstance(thread, (TraceWorker, LogWorker))
    ]
    for log_worker in log_workers:
        log_worker.stop(timeout=4)
    if len(log_workers) == 0:
        break
    time.sleep(2)
```

**Comment by lzchen** [comment]
Seems like Python logging library calls the following in order upon shutdown:

```python
                    h.acquire()
                    h.flush()
                    h.close()
```
where `h` is the global handler list. With [this](https://github.com/census-instrumentation/opencensus-python/blob/master/contrib/opencensus-ext-azure/opencensus/ext/azure/log_exporter/__init__.py#L96) being called in the `AzureLogHandler`, this issue should be solved.

**Comment by Willem-J-an** [comment]
Hi @lzchen,
I tried to get rid of my frankenstein by simply calling logging.shutdown(), but it only seems to work for the AzureLogHandler. This is an actual handler tied in with the logging infrastructure as a handler. AzureExporter on the other hand, does not get automatically shutdown, and my spans() do not get flushed on shutdown.

AzureExporter is not a log handler, but an exporter of a Tracer. As it seems to me, I should shut it down with tracer.finish();
Tracer.finish() calls BaseExporter.export(), which puts spans on the export queue, but does not flush or otherwise wait for the AzureExporter to finish. That leaves me no other way to flush / stop the thread other than asking for the private _worker of the exporter, or getting the thread directly to stop it.

**Comment by lzchen** [comment]
The `AzureExporter` is flushed [automatically](https://github.com/census-instrumentation/opencensus-python/blob/master/contrib/opencensus-ext-azure/opencensus/ext/azure/trace_exporter/__init__.py#L78) on application exit.

**Comment by Willem-J-an** [comment]
The atexit hook implementation is not dependable in all contexts. I run the code in databricks, and if I leave it to the autoexit spans only get flushed 60% of the time. I also find it a bit clunky just to wait for the interval and hope for the best.

**Comment by lzchen** [comment]
@Willem-J-an 

Makes sense. Feel free to create a feature request for manual flushing of the exporter.
