### ISSUE TITLE
Zipkin exporter sets incorrect localEndpoint.ipv4 for spans

### ISSUE THREAD

**Issue by wkiser** [census-instrumentation/opencensus-python#116]
The Zipkin exporter is currently setting the destination Zipkin server's hostname as the ipv4 on spans [here](https://github.com/census-instrumentation/opencensus-python/blob/master/opencensus/trace/exporters/zipkin_exporter.py#L129). It should instead be using the hostname/ip of the local host. The [python jaeger client](https://github.com/jaegertracing/jaeger-client-python) uses a good strategy for determining the local ip/hostname in [utils.py](https://github.com/jaegertracing/jaeger-client-python/blob/master/jaeger_client/utils.py#L61)

**Comment by adriancole** [comment]
Normally, we use a path to the full endpoint because people end up
re-mapping sometimes over TLS and it is easier than manually changing the
scheme host port and path.

ex

/**
* No default. The POST URL for zipkin's <a href="
http://zipkin.io/zipkin-api/#/">v2 api</a>,
* usually "http://zipkinhost:9411/api/v2/spans"
*/
// customizable so that users can re-map /api/v2/spans ex for
browser-originated traces
public final Builder endpoint(String endpoint) {

**Comment by wkiser** [comment]
Hey @adriancole, I just realized that I put the wrong line number in my initial issue. The issue I am having is that the census exporter sets the exported span's localEndpoint.ipv4 to be the Zipkin server's hostname [here](https://github.com/census-instrumentation/opencensus-python/blob/master/opencensus/trace/exporters/zipkin_exporter.py#L129). Unless I am missing something, I would expect the localEndpoint.ipv4 to be the ip of the machine executing the traced code.

I do agree that it would be better to configure the exporter with the full server endpoint, though.

**Comment by adriancole** [comment]
Makes sense (ps can also be ipv6) in either case raw ip and optional

**Comment by liyanhui1228** [comment]
I'm going to close this issue for now as we add support for setting the ipv4/ipv6 in ZipkinExporter.
