### ISSUE TITLE
Change to use pytest

### ISSUE THREAD

**Issue by liyanhui1228** [census-instrumentation/opencensus-python#2]

**Comment by zoidbergwill** [comment]
This looks done?

**Comment by duggelz** [comment]
No, things like `https://github.com/census-instrumentation/opencensus-python/blob/master/tests/unit/trace/test_config_integration.py` still use `unittest`-style tests instead of `pytest`-style tests.

**Comment by zoidbergwill** [comment]
Great point. Thanks. I was looking for issues I could possibly help with when I stumbled on this one, would it be useful for me to work on it? I don't wanna step on anyone's toes.

**Comment by duggelz** [comment]
This probably isn't the most useful thing to work on.

The existing tests are fine, and as you note, we already switched to running tests via `pytest`.  `unittest` and `pytest` coexist happily, so new tests can be written in pytest when desired, and old tests that are being modified or refactored can be updated to pytest at that time.  The benefits are fairly minor and not really worth a bunch of code churn right now.

I'm going to close this issue since writing pytest-style tests is possible.

**Comment by zoidbergwill** [comment]
Thanks, Douglas.

I'm keen to contribute, so I'll try find something more useful then.
