### ISSUE TITLE
wrapt dependency still missing

### ISSUE THREAD

**Issue by MikeRoetgers** [census-instrumentation/opencensus-python#210]
Hello,

I know this was already discussed in https://github.com/census-instrumentation/opencensus-python/issues/142. Could someone add the `wrapt` dependency to the next release? :slightly_smiling_face: 
Just picked up opencensus and stumbled over this instantly. The warning unfortunately isn't really prepared to handle this case either (`Failed to integrate module: requests, supported integrations are httplib, mysql, postgresql, pymysql, requests, sqlalchemy, google_cloud_clientlibs`).

Thank you!
Mike

**Comment by olance** [comment]
Allow me to bump this – the original issue (#142) is going to be a year old very soon and is just about correctly including a dependency with the package.

Meanwhile, It's biting 100% of your lib's users on first use

**Comment by c24t** [comment]
I added this in #432. You have to install the package as `opencensus[requests]` if you want the optional dependencies for requests since we don't want users that aren't using requests to install dependencies they don't need.

We may move each integration into its own distribution (see #445), which would solve the optional dependency problem; you'd install `opencensus-requests` separately instead.

**Comment by olance** [comment]
@c24t thanks and sorry for the noise!
Having separate packages for the different intégrations would make total sense :)

**Comment by reyang** [comment]
Now we have the wrapt dependency here https://github.com/census-instrumentation/opencensus-python/blob/master/contrib/opencensus-ext-requests/setup.py#L43.

The requests module is in its own distribution, which can be installed using `pip install opencensus-ext-requests`.
