### ISSUE TITLE
Allow arbitrary metric prefixes

### ISSUE THREAD

**Issue by mayurkale22** [census-instrumentation/opencensus-python#311]
Today OpenCensus Python only supports custom.googleapis.com domain prefix but Stackdriver supports more prefixes (and it's expanding). OC should not enforce metric prefix validation (There will never be a way to statically know the set of prefixes), we should allow users to report metrics for their registered domain.

https://github.com/census-instrumentation/opencensus-python/blob/dfae33d14d48a7a23ef25b8ac886acfcccfe3ee7/opencensus/stats/exporters/stackdriver_exporter.py#L352

**Comment by eddie-scio** [comment]
In case anyone is Googling around -- if you provide an arbitrary`metric_prefix` to the `stats_exporter.Options`, you may get a 403 from Stackdriver, something like `PermissionDenied: 403 User foo@bar.com does not have permission to write to metric <metric_prefix>/<metric_path>.`.  The solution is to prefix your own prefix with `custom.googleapis.com`.  Seems like [the docs](https://cloud.google.com/monitoring/custom-metrics/creating-metrics#custom_metric_names) allude to this: "The string must begin with a prefix that marks it as a user-defined metric. For Monitoring, the most common prefix is custom.googleapis.com/, though external.googleapis.com/ is also used. "

My 2c is that given the above behavior, I'm not sure that the implementation of this issue is the right thing to do.  Or at least maybe it should be better documented in the Opencensus code that Stackdriver expects certain prefixes.
