### ISSUE TITLE
Pin dependencies

### ISSUE THREAD

**Issue by c24t** [census-instrumentation/opencensus-python#387]
We're pinning some package versions in [requirements-text.txt](https://github.com/census-instrumentation/opencensus-python/blob/master/requirements-test.txt), but not *those* packages' dependencies. Consider using [pip-tools](https://github.com/jazzband/pip-tools) to pin all packages in the environment.

This issue was motivated by #334.

**Comment by reyang** [comment]
This is solved by #445.

**Comment by c24t** [comment]
#445 means we're installing fewer packages, but we're still not pinning the versions of the packages (just `'google-api-core` in the core library, plenty of others in the contrib packages) that we do install. 

We may not want to pin our dependencies in our setup files since that's likely to cause dependency conflicts for our users, but we may want to do it for our testing requirements to get deterministic builds.

**Comment by reyang** [comment]
Thanks for the clarification. The approach we take today is to use the latest version (based on the dependencies specified either in `setup.py` or `nox.py`).
This has pros and cons, the cons - as you mentioned - is undeterministic CI due to external package version change; the pros is we are always up-to-date and we know what is breaking (so we can fix them quickly).

Using fixed version (e.g. requirements.txt or vendoring in Golang) is a common solution for application developers, who want to lock everything for shipping / deployment. For libraries I guess taking the current approach makes more sense? (e.g. we don't need to keep an eye on every new version of dependency release, and decide when to upgrade or not, customers can also expect the support is up-to-date)

**Comment by reyang** [comment]
#635 removed the `requirements-test.txt` and started to use the *latest version*.
One motivation is to leverage the latest tools instead of having to manually maintain the harness version (by paying the cost of potential break caused by harness updates).
Another motivation is to get rid of the runtime version problem, e.g. we want to use lib x version n for Python3, while for Python2 the lastest version of x is n-2.

**Comment by reyang** [comment]
This is one unsolved problem - how to test against multiple major versions of an integration.
One great example is Django 1 and 2, which we encountered in #603.

**Comment by c24t** [comment]
One option is to parameterize the tests with nox, the same way we test against multiple python versions now, but it's not clear that the benefit is worth the extra complexity and maintenance time. I agree that libraries should generally be liberal with their dependencies and leave it up to app developers to lock down specific versions, but this means that (1) our own tests are vulnerable to version changes and (2) we're not necessarily testing against the same versions of packages that the end application is using.

There may not be a better solution than the one we've got now.
