### ISSUE TITLE
Don't expose mutable view data

### ISSUE THREAD

**Issue by c24t** [census-instrumentation/opencensus-python#470]
`MeasureToViewMap` exposes mutable `ViewData`s to exporters. Consider exporting a immutable view of `ViewData` instead. 

See https://github.com/census-instrumentation/opencensus-python/pull/469#discussion_r251619805 for some context.

**Comment by tchiotludo** [comment]
Just for my information, why do you close this tasks ? 

I see that the master branch still contains this comment : https://github.com/census-instrumentation/opencensus-python/blob/master/opencensus/stats/measure_to_view_map.py#L155
```python
    # TODO(issue #470): remove this method once we export immutable stats.
    def copy_and_finalize_view_data(self, view_data):
        view_data_copy = copy.copy(view_data)
        tvdam_copy = copy.deepcopy(view_data.tag_value_aggregation_data_map)
        view_data_copy._tag_value_aggregation_data_map = tvdam_copy
        view_data_copy.end()
        return view_data_copy
```

here is a simply version 


This leads for us to some exception on our production server : 

```
RuntimeError: dictionary changed size during iteration
at _deepcopy_dict (/usr/local/lib/python3.7/copy.py:239)
at deepcopy (/usr/local/lib/python3.7/copy.py:150)
at copy_and_finalize_view_data (/root/.local/lib/python3.7/site-packages/opencensus/stats/measure_to_view_map.py:158)
at <listcomp> (/root/.local/lib/python3.7/site-packages/opencensus/stats/measure_to_view_map.py:129)
at export (/root/.local/lib/python3.7/site-packages/opencensus/stats/measure_to_view_map.py:129)
at record (/root/.local/lib/python3.7/site-packages/opencensus/stats/measure_to_view_map.py:123)
at record (/root/.local/lib/python3.7/site-packages/opencensus/stats/measurement_map.py:118)
at measure (/app/api/services/google/opencensus_service.py:152)
```

Here is simplied version of code `opencensus_service.py:152`

```python 

        mmap: MeasurementMap = stats.stats.stats_recorder.new_measurement_map()
        tmap: Union[None, TagMap] = None
        
        mmap.measure_float_put(metric, value)

        if tags is not None and len(tags) > 0:
            tmap = tag_map_module.TagMap()
            for tag_key, tag_name in tags.items():
                tmap.insert(self._labels[tag_key], tag_value_module.TagValue(tag_name))

        mmap.record(tags=tmap) # lign 152 here
```

For now, we need to add a ugly try catch during the record to avoid metric to crash our app.

**Comment by lofifnc** [comment]
We're having the same problems it's so bad we had to stop writing metrics.

**Comment by JoshKarpel** [comment]
Hi, checking in on this - it's been a few years since this was active, but it looks like the `copy_and_finalize_view_data()` method is still in recent releases https://github.com/census-instrumentation/opencensus-python/blob/2e0710bf9ef733f29607418e51f0719422155361/opencensus/stats/measure_to_view_map.py#L157-L163

We're using `opencensus` through https://github.com/ray-project/ray, which is using it to gather metrics on worker processes on its nodes. We're seeing the process that is responsible for those metrics pinned at 100% CPU usage with ~85% of time spent in `copy_and_finalize_view_data()` (flamegraph taken using `py-spy`).

![image](https://github.com/census-instrumentation/opencensus-python/assets/7133863/d311d671-375f-4afd-b27c-9f3a4df8cca5)

Given the serious performance impact of copying so much data, can this hopefully-now-unnecessary code actually be removed?

cc @lzchen since you seem to be the most active current maintainer.
