### ISSUE TITLE
Support int export for sum and lastvalue aggregations

### ISSUE THREAD

**Issue by c24t** [census-instrumentation/opencensus-python#565]
`LastValueAggregationData` and `SumAggregationDataFloat` are always converted to a float-valued metrics. This makes metric conversion impossible for views with `MeasureInt` measures.

The java client uses multiple classes (e.g. [`MutableSumLong` and `MutableSumDouble`](https://github.com/c24t/opencensus-java/blob/master/impl_core/src/main/java/io/opencensus/implcore/stats/MutableAggregation.java)) to solve this problem.

**Comment by colincadams** [comment]
Is this likely to be addressed soon or is it on the backlog?

If it's on the backlog and I find some time in the next week or so I can take a pass at it.

**Comment by c24t** [comment]
@colincadams it's on my todo list, but feel free to pick it up!

**Comment by colincadams** [comment]
Alright, I've been thinking through this and messing around with it a bit in my free time. My current plan for addressing this is:

* Turn `aggregation` into a factory of `aggregation_data`
* Add a `value_type` parameter to `aggregation_data`

e.g.
```python
class AggregationData:
  def __init__(value_type):
    self._value_type = value_type

  def to_point(self, timestamp):
    return point.Point(self._value_type(self.value), timestamp)

class Aggregation:
  def new_aggregation_data(measure):
    value_type = measure_to_value_type_magic(measure)
    return AggregationData(value_type, ...)
```

The reason for this approach is that the caller creates the aggregation object, so at that point we don't know the type of the measure. This could be changed so that the caller just passes an aggregation class to the view instead of an instance, but that prevents them from defining any initial values (is that something we want to support?! it currently is so I've left it that way).

We currently store an `AggregationData` in `Aggregation`, and then whenever a view needs to create a new one it calls deep copies it, so calling a factory method on it instead seems reasonable to me. WDYT? Is it odd to have to pass the measure into this method?

We could instead just pass the value type into `to_point`, but that prevents us to have behavior inside of `AggregationData` based on the value type (i.e. casting). We could also have the caller create an aggregation of the appropriate type but that feels unnecessary.

**Comment by colincadams** [comment]
@c24t thoughts on this?

**Comment by c24t** [comment]
Passing the aggregation _class_ to `View` and then creating the right type of `AggregationData` on the fly sounds like exactly the right solution to me. Would you expect to move the mutable attrs and `add_sample` from `AggregationData` classes into the `Aggregation`s and make `AggregationData`s immutable?

> that prevents them from defining any initial values (is that something we want to support?!

I think it's fine to lose initial values, but I'll see if I can find a use case for it. We may be able to lose the default arguments to `Aggregation`s altogether since `aggregation_type` doesn't give us any information we can't get from the class, and I don't see any reason a user would change it.

Why store `value_type` on `AggregationData` instead of `Aggregation`? FWIW I think we want separate `AggregationData` classes  (i.e. `SumAggregationDataInt`, `SumAggregationDataFloat`, `LastValueAggregationDataInt`, and `LastValueAggregationDataFloat`) for each value type so we don't have to inspect the data when we e.g. convert it to a metric.

**Comment by c24t** [comment]
For completeness it seems like we should support int values to `DistributionAggregation`s too -- this would produce `ValueDistribution`s with int-valued `sum`s. I don't see this in the other clients, but it may be worth keeping in mind.

**Comment by c24t** [comment]
In case it helps, here's an ipython notebook to reproduce the export failure: https://gist.github.com/c24t/09658c30c2d6bf6a1cc95bfbff55d3ca#file-ocp-int-agg-failure-565-ipynb

**Comment by c24t** [comment]
Also see https://github.com/census-instrumentation/opencensus-python/issues/388#issuecomment-436804857.

**Comment by whitemike889** [comment]
##
