### ISSUE TITLE
AttributeError: module 'opencensus.stats.stats' has no attribute 'Stats'

### ISSUE THREAD

**Issue by zyxue** [census-instrumentation/opencensus-python#941]
I'm following the Python example on https://opencensus.io/stats/view/#2

```
>>> from opencensus.stats import stats
>>> view_manager = stats.Stats().view_manager
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'opencensus.stats.stats' has no attribute 'Stats'
```

Reading https://github.com/census-instrumentation/opencensus-python/blob/f4d8ec36cada8b385821a16795f27fe322694a1a/opencensus/stats/stats.py#L22,

`Stats` seems to have been protected as `_Stats`, what's the current recommended way to start a view manager, please?

**Comment by lzchen** [comment]
`view_manager = stats.view_manager`

It is a global variable.

**Comment by zyxue** [comment]
Curious why is global variable used? I thought something like `view_manager = stats.Stats().view_manager` would be more preferable?

**Comment by lzchen** [comment]
I'm not sure if having multiple instances of `Stats`/`ViewManager` would be preferable. Having a global variable and all `View`s registered through that one instance makes it so that we do not have to have additional configuration api as part of the metrics pipeline. For example, if I have multiple ViewManagers, and I add different views for each of them, how would I know which ones to pull from to export metrics? I would have to "attach" ViewManagers to exporters.

**Comment by rpavlov** [comment]
Basically all of the code examples and documentation referencing how to use Stats() are wrong.

**Comment by lzchen** [comment]
@rpavlov 
Can you provide an example?
