### ISSUE TITLE
google-cloud-trace 1.0.0 is not working with StackdriverExporter

### ISSUE THREAD

**Issue by Natim** [census-instrumentation/opencensus-python#954]
```
opencensus/ext/stackdriver/trace_exporter/__init__.py:18: in <module>

from google.cloud.trace.client import Client
E   ModuleNotFoundError: No module named 'google.cloud.trace.client'`
```

**Comment by aabmass** [comment]
@Natim the version is correctly specified in `setup.py` by the looks of it https://github.com/census-instrumentation/opencensus-python/blob/6721a56597a4a3907a7c0c06d1a3de2c9da87c11/contrib/opencensus-ext-stackdriver/setup.py#L43

How did you encounter this issue?

**Comment by Natim** [comment]
Hello @aabmass I guess it is because I use google-cloud-trace not only as an opencensus dependency but as a project dependency too.

**Comment by aabmass** [comment]
@Natim, unfortunately google-cloud-trace 1.0.0 only supports Python >= 3.6 so we need to keep that old version.

**Comment by hilliao** [comment]
I had to put a version range in [my requirements.txt](https://github.com/hilliao/enterprise-solutions/commit/62af8ea4921297c60411636064b52ca0ed0e3e5f#diff-bd8d50da46c120c620a9da26c2596a5a) because pip3 install would get google-cloud-trace 1.0.0 by default. Is the reason of [code](https://github.com/census-instrumentation/opencensus-python/blob/6721a56597a4a3907a7c0c06d1a3de2c9da87c11/contrib/opencensus-ext-stackdriver/setup.py#L43) ` 'google-cloud-trace >= 0.20.0, < 1.0.0', ` to support Python < 3.6?

**Comment by Natim** [comment]
I think even if google-cloud-trace support Python 3.6+ we can support both version here with a try catch to handle both imports:

```
try:
   from google.cloud.trace_v2.services.trace_service import TraceServiceClient as Client  # v 1.0
except ImportError:
   # fallback for google-cloud-trace < 1.0
   from google.cloud.trace.client import Client
```

**Comment by busunkim96** [comment]
@aabmass Do you all have a timeline for dropping 2.7 support?

**Comment by aabmass** [comment]
We don't have plans to drop 2.7 as OC is in maintenance mode with OpenTelemetry replacing it.
